"""The recording-context compiler (DESIGN §5, §7.2) — the M1 core.

Public surface used by the pipeline, the CLI, and the follow-on M1 workstreams:

- :func:`compile_bundle` / :func:`compile_registered` / :class:`CompileResult`
- the recording verbs (:func:`when`, :func:`only_if`) and the ``@automation`` /
  ``@script`` decorators
- the M1-core builders (:func:`state`, :func:`service`, :func:`delay`)
- the extension-point protocols (:class:`TriggerBuilder` / :class:`ConditionBuilder`
  / :class:`ActionBuilder`) and the record functions the builder families call
- the compile errors (:class:`CompileTimeBranchError` et al.)
- :class:`SourceSpan`

Import the *user-facing* names from the top-level :mod:`hassle` package instead;
this module is the implementation home.
"""

from __future__ import annotations

from hassle_core.compiler.action_verbs import event, service_ext, stop, variables
from hassle_core.compiler.actions import delay, service
from hassle_core.compiler.builders import (
    DelayAction,
    ServiceAction,
    StateExpr,
    state,
)
from hassle_core.compiler.bundle import (
    CompileResult,
    compile_bundle,
    compile_registered,
)
from hassle_core.compiler.conditions import (
    TriggerConditionExpr,
    all_of,
    any_of,
    not_,
    trigger_condition,
)
from hassle_core.compiler.control_flow import (
    choose,
    else_if,
    else_then,
    if_then,
    parallel,
    repeat_count,
    repeat_for_each,
    repeat_until,
    repeat_while,
    wait_for,
    wait_template,
)
from hassle_core.compiler.durations import hours, minutes, normalize_duration, seconds
from hassle_core.compiler.errors import (
    CompileError,
    CompileTimeBranchError,
    DuplicateObjectError,
    ElseWithoutIfError,
    NoRecordingContextError,
    UnknownAutomationOptionError,
)
from hassle_core.compiler.macros import macro
from hassle_core.compiler.protocols import (
    ActionBuilder,
    ConditionBuilder,
    TriggerBuilder,
)
from hassle_core.compiler.purpose import (
    AreaTarget,
    DeviceIdTarget,
    FloorTarget,
    LabelTarget,
    PurposeCondition,
    PurposeTrigger,
    area,
    device_id,
    floor,
    label,
    met,
    on,
)
from hassle_core.compiler.raw import (
    RawAction,
    RawCondition,
    RawTrigger,
    raw_action,
    raw_condition,
    raw_trigger,
)
from hassle_core.compiler.recording import (
    RecordedNode,
    Recorder,
    only_if,
    record_action,
    record_condition,
    record_trigger,
    recording,
    when,
)
from hassle_core.compiler.registry import (
    RegisteredObject,
    Registry,
    automation,
    current_registry,
    fresh,
    script,
)
from hassle_core.compiler.scripts import (
    NoParamContextError,
    ScriptCallAction,
    UnknownParamError,
    param,
    shared_script,
)
from hassle_core.compiler.spans import SourceSpan, capture_span
from hassle_core.compiler.templates import expr
from hassle_core.compiler.triggers import (
    CalendarTrigger,
    DeviceTrigger,
    EventTrigger,
    GeoLocationTrigger,
    HomeAssistantTrigger,
    MqttTrigger,
    NumericStateExpr,
    PersistentNotificationTrigger,
    SunExpr,
    TagTrigger,
    TemplateExpr,
    TimeExpr,
    TimePatternTrigger,
    TriggerWithOptions,
    WebhookTrigger,
    ZoneExpr,
    calendar,
    device,
    geo_location,
    homeassistant_shutdown,
    homeassistant_start,
    mqtt,
    numeric_state,
    persistent_notification,
    sun,
    tag,
    template,
    time,
    time_pattern,
    webhook,
    with_trigger_options,
    zone,
)

__all__ = [
    "ActionBuilder",
    "AreaTarget",
    "CalendarTrigger",
    "CompileError",
    "CompileResult",
    "CompileTimeBranchError",
    "ConditionBuilder",
    "DelayAction",
    "DeviceIdTarget",
    "DeviceTrigger",
    "DuplicateObjectError",
    "ElseWithoutIfError",
    "EventTrigger",
    "FloorTarget",
    "GeoLocationTrigger",
    "HomeAssistantTrigger",
    "LabelTarget",
    "MqttTrigger",
    "NoParamContextError",
    "NoRecordingContextError",
    "NumericStateExpr",
    "PersistentNotificationTrigger",
    "PurposeCondition",
    "PurposeTrigger",
    "RawAction",
    "RawCondition",
    "RawTrigger",
    "RecordedNode",
    "Recorder",
    "RegisteredObject",
    "Registry",
    "ScriptCallAction",
    "ServiceAction",
    "SourceSpan",
    "StateExpr",
    "SunExpr",
    "TagTrigger",
    "TemplateExpr",
    "TimeExpr",
    "TimePatternTrigger",
    "TriggerBuilder",
    "TriggerConditionExpr",
    "TriggerWithOptions",
    "UnknownAutomationOptionError",
    "UnknownParamError",
    "WebhookTrigger",
    "ZoneExpr",
    "all_of",
    "any_of",
    "area",
    "automation",
    "calendar",
    "capture_span",
    "choose",
    "compile_bundle",
    "compile_registered",
    "current_registry",
    "delay",
    "device",
    "device_id",
    "else_if",
    "else_then",
    "event",
    "expr",
    "floor",
    "fresh",
    "geo_location",
    "homeassistant_shutdown",
    "homeassistant_start",
    "hours",
    "if_then",
    "label",
    "macro",
    "met",
    "minutes",
    "mqtt",
    "normalize_duration",
    "not_",
    "numeric_state",
    "on",
    "only_if",
    "parallel",
    "param",
    "persistent_notification",
    "raw_action",
    "raw_condition",
    "raw_trigger",
    "record_action",
    "record_condition",
    "record_trigger",
    "recording",
    "repeat_count",
    "repeat_for_each",
    "repeat_until",
    "repeat_while",
    "script",
    "seconds",
    "service",
    "service_ext",
    "shared_script",
    "state",
    "stop",
    "sun",
    "tag",
    "template",
    "time",
    "time_pattern",
    "trigger_condition",
    "variables",
    "wait_for",
    "wait_template",
    "webhook",
    "when",
    "with_trigger_options",
    "zone",
]
