"""Generated by `hassle stubs` from the registry snapshot. Do not edit by hand."""

from __future__ import annotations

class AlarmControlPanelEntity: ...

class AutomationEntity:
    def trigger(self, skip_condition: bool | str = ...) -> None: ...

class BinarySensorEntity: ...
class ButtonEntity: ...
class CalendarEntity: ...
class CameraEntity: ...

class ClimateEntity:
    def set_temperature(self, temperature: float | str = ...) -> None: ...

class CounterEntity: ...
class CoverEntity: ...
class DeviceTrackerEntity: ...
class EventEntity: ...

class FanEntity:
    def turn_off(self) -> None: ...
    def turn_on(self, percentage: int | str = ...) -> None: ...

class GeoLocationEntity: ...
class HumidifierEntity: ...
class ImageEntity: ...

class InputBooleanEntity:
    def toggle(self) -> None: ...
    def turn_off(self) -> None: ...
    def turn_on(self) -> None: ...

class InputButtonEntity: ...
class InputDatetimeEntity: ...
class InputNumberEntity: ...
class InputSelectEntity: ...
class InputTextEntity: ...

class LightEntity:
    def toggle(self) -> None: ...
    def turn_off(self, transition: float | str = ...) -> None: ...
    def turn_on(
        self,
        brightness: int | str = ...,
        brightness_pct: int | str = ...,
        color_temp: int | str = ...,
        transition: float | str = ...,
    ) -> None: ...

class LockEntity: ...
class MediaPlayerEntity: ...

class NotifyEntity:
    def notify(self, message: str = ..., title: str = ...) -> None: ...

class NumberEntity: ...
class PersonEntity: ...
class SceneEntity: ...

class ScheduleEntity:
    def reload(self) -> None: ...

class ScriptEntity:
    def turn_on(self) -> None: ...

class SelectEntity: ...
class SensorEntity: ...
class SirenEntity: ...
class SunEntity: ...

class SwitchEntity:
    def toggle(self) -> None: ...
    def turn_off(self) -> None: ...
    def turn_on(self) -> None: ...

class TimerEntity:
    def cancel(self) -> None: ...
    def start(self, duration: str = ...) -> None: ...

class UpdateEntity: ...

class VacuumEntity:
    def return_to_base(self) -> None: ...
    def start(self) -> None: ...

class WaterHeaterEntity: ...
class WeatherEntity: ...
class ZoneEntity: ...

class _AlarmControlPanel:
    home: AlarmControlPanelEntity  # alarm_control_panel.home - "Home Alarm"
    def __getitem__(self, object_id: str) -> AlarmControlPanelEntity: ...

class _Automation:
    hall_light_on_motion: AutomationEntity  # automation.hall_light_on_motion
    morning_lights: AutomationEntity  # automation.morning_lights - "Morning Lights"
    def __getitem__(self, object_id: str) -> AutomationEntity: ...

class _BinarySensor:
    alarm: BinarySensorEntity  # binary_sensor.alarm - "Alarm Sensor"
    back_door: BinarySensorEntity  # binary_sensor.back_door - "Back Door"
    basement_flood: BinarySensorEntity  # binary_sensor.basement_flood - "Basement Flood Sensor"
    bathroom_humidity: BinarySensorEntity  # binary_sensor.bathroom_humidity
    bedroom_motion: BinarySensorEntity  # binary_sensor.bedroom_motion - "Bedroom Motion"
    bedroom_window: BinarySensorEntity  # binary_sensor.bedroom_window - "Bedroom Window"
    door: BinarySensorEntity  # binary_sensor.door - "Front Door"
    front_door: BinarySensorEntity  # binary_sensor.front_door - "Front Door Sensor"
    garage_door: BinarySensorEntity  # binary_sensor.garage_door - "Garage Door"
    guest_arrived: BinarySensorEntity  # binary_sensor.guest_arrived - "Guest Arrived"
    guest_sensor: BinarySensorEntity  # binary_sensor.guest_sensor - "Guest Sensor"
    hall_motion: BinarySensorEntity  # binary_sensor.hall_motion - "Hall Motion"
    kitchen_motion: BinarySensorEntity  # binary_sensor.kitchen_motion - "Kitchen Motion"
    laundry_door: BinarySensorEntity  # binary_sensor.laundry_door - "Laundry Door"
    living_room_motion: BinarySensorEntity  # binary_sensor.living_room_motion
    motion: BinarySensorEntity  # binary_sensor.motion - "Motion"
    motion_detector: BinarySensorEntity  # binary_sensor.motion_detector - "Motion Detector"
    office_motion: BinarySensorEntity  # binary_sensor.office_motion - "Office Motion"
    trigger: BinarySensorEntity  # binary_sensor.trigger - "Test Trigger Sensor"
    window: BinarySensorEntity  # binary_sensor.window - "Window Sensor"
    workshop_door: BinarySensorEntity  # binary_sensor.workshop_door - "Workshop Door"
    def __getitem__(self, object_id: str) -> BinarySensorEntity: ...

class _Button:
    reboot_ha: ButtonEntity  # button.reboot_ha - "Reboot HA"
    restart: ButtonEntity  # button.restart - "Restart"
    start: ButtonEntity  # button.start - "Start Button"
    test: ButtonEntity  # button.test - "Test Button"
    def __getitem__(self, object_id: str) -> ButtonEntity: ...

class _Calendar:
    holidays: CalendarEntity  # calendar.holidays - "Holidays"
    work_schedule: CalendarEntity  # calendar.work_schedule - "Work Schedule"
    def __getitem__(self, object_id: str) -> CalendarEntity: ...

class _Camera:
    back_patio: CameraEntity  # camera.back_patio - "Back Patio Camera"
    driveway: CameraEntity  # camera.driveway - "Driveway Camera"
    front_door: CameraEntity  # camera.front_door - "Front Door Camera"
    garage_interior: CameraEntity  # camera.garage_interior - "Garage Interior Camera"
    living_room: CameraEntity  # camera.living_room - "Living Room Camera"
    side_yard: CameraEntity  # camera.side_yard - "Side Yard Camera"
    def __getitem__(self, object_id: str) -> CameraEntity: ...

class _Climate:
    bedroom_thermostat: ClimateEntity  # climate.bedroom_thermostat - "Bedroom Thermostat"
    living: ClimateEntity  # climate.living - "Living Climate"
    living_room: ClimateEntity  # climate.living_room - "Living Room Thermostat"
    office_thermostat: ClimateEntity  # climate.office_thermostat - "Office Thermostat"
    def __getitem__(self, object_id: str) -> ClimateEntity: ...

class _Counter:
    daily_count: CounterEntity  # counter.daily_count - "Daily Count"
    def __getitem__(self, object_id: str) -> CounterEntity: ...

class _Cover:
    basement_window: CoverEntity  # cover.basement_window - "Basement Window"
    bathroom_exhaust_damper: CoverEntity  # cover.bathroom_exhaust_damper
    bedroom_blinds: CoverEntity  # cover.bedroom_blinds - "Bedroom Blinds"
    garage_door: CoverEntity  # cover.garage_door - "Garage Door"
    kitchen_blinds: CoverEntity  # cover.kitchen_blinds - "Kitchen Blinds"
    living_room_blinds: CoverEntity  # cover.living_room_blinds - "Living Room Blinds"
    living_room_shade: CoverEntity  # cover.living_room_shade - "Living Room Shade"
    office_blinds: CoverEntity  # cover.office_blinds - "Office Blinds"
    def __getitem__(self, object_id: str) -> CoverEntity: ...

class _DeviceTracker:
    john: DeviceTrackerEntity  # device_tracker.john - "John"
    john_phone: DeviceTrackerEntity  # device_tracker.john_phone - "John's Phone"
    keaton_phone: DeviceTrackerEntity  # device_tracker.keaton_phone - "Keaton's Phone"
    def __getitem__(self, object_id: str) -> DeviceTrackerEntity: ...

class _Event:
    doorbell: EventEntity  # event.doorbell - "Doorbell"
    garage_motion: EventEntity  # event.garage_motion - "Garage Motion"
    def __getitem__(self, object_id: str) -> EventEntity: ...

class _Fan:
    bedroom: FanEntity  # fan.bedroom - "Bedroom Fan"
    kitchen_fan: FanEntity  # fan.kitchen_fan - "Kitchen Fan"
    living_room: FanEntity  # fan.living_room - "Living Room Fan"
    living_room_ceiling: FanEntity  # fan.living_room_ceiling - "Living Room Ceiling Fan"
    office_fan: FanEntity  # fan.office_fan - "Office Fan"
    def __getitem__(self, object_id: str) -> FanEntity: ...

class _GeoLocation:
    mobile_device: GeoLocationEntity  # geo_location.mobile_device - "Mobile Device"
    def __getitem__(self, object_id: str) -> GeoLocationEntity: ...

class _Humidifier:
    bedroom: HumidifierEntity  # humidifier.bedroom - "Bedroom Humidifier"
    living_room: HumidifierEntity  # humidifier.living_room - "Living Room Humidifier"
    def __getitem__(self, object_id: str) -> HumidifierEntity: ...

class _Image:
    front_door: ImageEntity  # image.front_door - "Front Door Camera"
    def __getitem__(self, object_id: str) -> ImageEntity: ...

class _InputBoolean:
    armed: InputBooleanEntity  # input_boolean.armed - "Armed"
    away: InputBooleanEntity  # input_boolean.away - "Away"
    do_not_disturb: InputBooleanEntity  # input_boolean.do_not_disturb - "Do Not Disturb"
    done: InputBooleanEntity  # input_boolean.done - "Done"
    enable: InputBooleanEntity  # input_boolean.enable - "Enable"
    enable_automation: InputBooleanEntity  # input_boolean.enable_automation - "Enable Automation"
    guest_mode: InputBooleanEntity  # input_boolean.guest_mode - "Guest Mode"
    holiday_mode: InputBooleanEntity  # input_boolean.holiday_mode - "Holiday Mode"
    mode: InputBooleanEntity  # input_boolean.mode - "Mode Toggle"
    def __getitem__(self, object_id: str) -> InputBooleanEntity: ...

class _InputButton:
    reset: InputButtonEntity  # input_button.reset - "Reset"
    def __getitem__(self, object_id: str) -> InputButtonEntity: ...

class _InputDatetime:
    alarm_time: InputDatetimeEntity  # input_datetime.alarm_time - "Alarm Time"
    def __getitem__(self, object_id: str) -> InputDatetimeEntity: ...

class _InputNumber:
    counter: InputNumberEntity  # input_number.counter - "Counter Input"
    max_temperature: InputNumberEntity  # input_number.max_temperature - "Max Temperature"
    target_temp: InputNumberEntity  # input_number.target_temp - "Target Temperature"
    def __getitem__(self, object_id: str) -> InputNumberEntity: ...

class _InputSelect:
    house_mode: InputSelectEntity  # input_select.house_mode - "House Mode"
    mode: InputSelectEntity  # input_select.mode - "Mode"
    def __getitem__(self, object_id: str) -> InputSelectEntity: ...

class _InputText:
    entities: InputTextEntity  # input_text.entities - "Entities List"
    location: InputTextEntity  # input_text.location - "Location"
    material_you_image_url_6814bc: InputTextEntity  # input_text.material_you_image_url_6814bc
    vacation_note: InputTextEntity  # input_text.vacation_note - "Vacation Note"
    def __getitem__(self, object_id: str) -> InputTextEntity: ...

class _Light:
    a: LightEntity  # light.a - "Light A"
    all: LightEntity  # light.all - "All Lights"
    all_downstairs: LightEntity  # light.all_downstairs - "All Downstairs"
    b: LightEntity  # light.b - "Light B"
    back_patio: LightEntity  # light.back_patio - "Back Patio"
    basement: LightEntity  # light.basement - "Basement"
    bathroom: LightEntity  # light.bathroom - "Bathroom"
    bathroom_mirror: LightEntity  # light.bathroom_mirror - "Bathroom Mirror"
    bedroom: LightEntity  # light.bedroom - "Bedroom"
    entryway: LightEntity  # light.entryway - "Entryway Light"
    front_door_light: LightEntity  # light.front_door_light - "Front Door Light"
    garage_ceiling: LightEntity  # light.garage_ceiling - "Garage Ceiling"
    hallway: LightEntity  # light.hallway - "Hallway"
    kitchen: LightEntity  # light.kitchen - "Kitchen"
    kitchen_island: LightEntity  # light.kitchen_island - "Kitchen Island"
    kitchen_under_cabinet: LightEntity  # light.kitchen_under_cabinet - "Kitchen Under Cabinet"
    laundry_room: LightEntity  # light.laundry_room - "Laundry Room"
    living_room: LightEntity  # light.living_room - "Living Room"
    living_room_accent: LightEntity  # light.living_room_accent - "Living Room Accent"
    master_bedroom_bedside: LightEntity  # light.master_bedroom_bedside - "Master Bedroom Bedside"
    master_bedroom_ceiling: LightEntity  # light.master_bedroom_ceiling - "Master Bedroom Ceiling"
    mudroom: LightEntity  # light.mudroom - "Mudroom"
    office: LightEntity  # light.office - "Office Light"
    office_ceiling: LightEntity  # light.office_ceiling - "Office Ceiling"
    office_desk: LightEntity  # light.office_desk - "Office Desk"
    porch: LightEntity  # light.porch - "Porch"
    side_yard: LightEntity  # light.side_yard - "Side Yard"
    utility_room: LightEntity  # light.utility_room - "Utility Room"
    workshop: LightEntity  # light.workshop - "Workshop"
    def __getitem__(self, object_id: str) -> LightEntity: ...

class _Lock:
    back_door: LockEntity  # lock.back_door - "Back Door Lock"
    front_door: LockEntity  # lock.front_door - "Front Door Lock"
    garage_entry_door: LockEntity  # lock.garage_entry_door - "Garage Entry Door Lock"
    garage_side_door: LockEntity  # lock.garage_side_door - "Garage Side Door Lock"
    office_door: LockEntity  # lock.office_door - "Office Door Lock"
    def __getitem__(self, object_id: str) -> LockEntity: ...

class _MediaPlayer:
    bathroom_speaker: MediaPlayerEntity  # media_player.bathroom_speaker - "Bathroom Speaker"
    bedroom_speaker: MediaPlayerEntity  # media_player.bedroom_speaker - "Bedroom Speaker"
    bedroom_tv: MediaPlayerEntity  # media_player.bedroom_tv - "Bedroom TV"
    kitchen_speaker: MediaPlayerEntity  # media_player.kitchen_speaker - "Kitchen Speaker"
    living_room_speaker: MediaPlayerEntity  # media_player.living_room_speaker
    office_speaker: MediaPlayerEntity  # media_player.office_speaker - "Office Speaker"
    tv: MediaPlayerEntity  # media_player.tv - "Living Room TV"
    def __getitem__(self, object_id: str) -> MediaPlayerEntity: ...

class _Notify:
    mobile_app_keaton: NotifyEntity  # notify.mobile_app_keaton - "Mobile App Keaton"
    mobile_app_spouse: NotifyEntity  # notify.mobile_app_spouse - "Mobile App Spouse"
    notify: NotifyEntity  # notify.notify - "Notifications"
    phone: NotifyEntity  # notify.phone - "Phone Notification"
    def __getitem__(self, object_id: str) -> NotifyEntity: ...

class _Number:
    bedroom_brightness: NumberEntity  # number.bedroom_brightness - "Bedroom Brightness"
    kitchen_brightness_threshold: NumberEntity  # number.kitchen_brightness_threshold
    living_room_brightness: NumberEntity  # number.living_room_brightness - "Living Room Brightness"
    def __getitem__(self, object_id: str) -> NumberEntity: ...

class _Person:
    john: PersonEntity  # person.john - "John"
    keaton: PersonEntity  # person.keaton - "Keaton"
    def __getitem__(self, object_id: str) -> PersonEntity: ...

class _Scene:
    evening: SceneEntity  # scene.evening - "Evening Scene"
    def __getitem__(self, object_id: str) -> SceneEntity: ...

class _Schedule:
    morning_routine: ScheduleEntity  # schedule.morning_routine - "Morning Routine"
    def __getitem__(self, object_id: str) -> ScheduleEntity: ...

class _Script:
    bedtime: ScriptEntity  # script.bedtime - "Bedtime"
    good_morning: ScriptEntity  # script.good_morning - "Good Morning"
    greet_guest: ScriptEntity  # script.greet_guest - "Greet Guest"
    movie_time: ScriptEntity  # script.movie_time - "Movie Time"
    security_check: ScriptEntity  # script.security_check - "Security Check"
    def __getitem__(self, object_id: str) -> ScriptEntity: ...

class _Select:
    bedroom_scene: SelectEntity  # select.bedroom_scene - "Bedroom Scene"
    lighting_mode: SelectEntity  # select.lighting_mode - "Lighting Mode"
    living_room_scene: SelectEntity  # select.living_room_scene - "Living Room Scene"
    def __getitem__(self, object_id: str) -> SelectEntity: ...

class _Sensor:
    _3d_printer: SensorEntity  # sensor.3d_printer - "3D Printer"
    air_quality_indoor: SensorEntity  # sensor.air_quality_indoor - "Indoor Air Quality"
    basement_humidity: SensorEntity  # sensor.basement_humidity - "Basement Humidity"
    basement_temperature: SensorEntity  # sensor.basement_temperature - "Basement Temperature"
    bathroom_humidity: SensorEntity  # sensor.bathroom_humidity - "Bathroom Humidity"
    bedroom_humidity: SensorEntity  # sensor.bedroom_humidity - "Bedroom Humidity"
    bedroom_temperature: SensorEntity  # sensor.bedroom_temperature - "Bedroom Temperature"
    co2_level: SensorEntity  # sensor.co2_level - "CO2 Level"
    counter: SensorEntity  # sensor.counter - "Counter Sensor"
    energy_usage_today: SensorEntity  # sensor.energy_usage_today - "Energy Usage Today"
    front_porch_light_level: SensorEntity  # sensor.front_porch_light_level
    hall_motion: SensorEntity  # sensor.hall_motion - "Hall Motion Sensor"
    humidity: SensorEntity  # sensor.humidity - "Humidity"
    kitchen_sink_water: SensorEntity  # sensor.kitchen_sink_water - "Kitchen Sink Water"
    kitchen_temperature: SensorEntity  # sensor.kitchen_temperature - "Kitchen Temperature"
    living_room_temperature: SensorEntity  # sensor.living_room_temperature
    office_temperature: SensorEntity  # sensor.office_temperature - "Office Temperature"
    outdoor_temp: SensorEntity  # sensor.outdoor_temp - "Outdoor Temp"
    outdoor_temperature: SensorEntity  # sensor.outdoor_temperature - "Outdoor Temperature"
    solar_production: SensorEntity  # sensor.solar_production - "Solar Production"
    temperature: SensorEntity  # sensor.temperature - "Temperature"
    time_of_day: SensorEntity  # sensor.time_of_day - "Time of Day"
    uptime: SensorEntity  # sensor.uptime - "Uptime"
    washing_machine_power: SensorEntity  # sensor.washing_machine_power - "Washing Machine Power"
    wireless_device_battery: SensorEntity  # sensor.wireless_device_battery
    workshop_temperature: SensorEntity  # sensor.workshop_temperature - "Workshop Temperature"
    def __getitem__(self, object_id: str) -> SensorEntity: ...

class _Siren:
    garage_alarm: SirenEntity  # siren.garage_alarm - "Garage Alarm"
    def __getitem__(self, object_id: str) -> SirenEntity: ...

class _Sun:
    sun: SunEntity  # sun.sun - "Sun"
    def __getitem__(self, object_id: str) -> SunEntity: ...

class _Switch:
    bathroom_exhaust: SwitchEntity  # switch.bathroom_exhaust - "Bathroom Exhaust"
    bedroom_fan: SwitchEntity  # switch.bedroom_fan - "Bedroom Fan Power"
    coffee_maker: SwitchEntity  # switch.coffee_maker - "Coffee Maker"
    dryer: SwitchEntity  # switch.dryer - "Dryer"
    garage_door_opener: SwitchEntity  # switch.garage_door_opener - "Garage Door Opener"
    kitchen_outlet: SwitchEntity  # switch.kitchen_outlet - "Kitchen Outlet"
    living_room_tv: SwitchEntity  # switch.living_room_tv - "Living Room TV"
    office_monitor: SwitchEntity  # switch.office_monitor - "Office Monitor"
    porch: SwitchEntity  # switch.porch - "Porch Switch"
    pump: SwitchEntity  # switch.pump - "Pump Switch"
    washing_machine: SwitchEntity  # switch.washing_machine - "Washing Machine"
    workshop_outlet: SwitchEntity  # switch.workshop_outlet - "Workshop Outlet"
    def __getitem__(self, object_id: str) -> SwitchEntity: ...

class _Timer:
    kitchen: TimerEntity  # timer.kitchen - "Kitchen Timer"
    def __getitem__(self, object_id: str) -> TimerEntity: ...

class _Update:
    hass_os: UpdateEntity  # update.hass_os - "Home Assistant OS"
    home_assistant_core: UpdateEntity  # update.home_assistant_core - "Home Assistant Core"
    def __getitem__(self, object_id: str) -> UpdateEntity: ...

class _Vacuum:
    downstairs: VacuumEntity  # vacuum.downstairs - "Downstairs Vacuum"
    upstairs: VacuumEntity  # vacuum.upstairs - "Upstairs Vacuum"
    def __getitem__(self, object_id: str) -> VacuumEntity: ...

class _WaterHeater:
    main: WaterHeaterEntity  # water_heater.main - "Main Water Heater"
    def __getitem__(self, object_id: str) -> WaterHeaterEntity: ...

class _Weather:
    home: WeatherEntity  # weather.home - "Weather at home"
    hourly: WeatherEntity  # weather.hourly - "Hourly Weather"
    def __getitem__(self, object_id: str) -> WeatherEntity: ...

class _Zone:
    gym: ZoneEntity  # zone.gym - "Gym"
    home: ZoneEntity  # zone.home - "Home"
    work: ZoneEntity  # zone.work - "Work"
    def __getitem__(self, object_id: str) -> ZoneEntity: ...

class _EntitiesRegistry:
    alarm_control_panel: _AlarmControlPanel
    automation: _Automation
    binary_sensor: _BinarySensor
    button: _Button
    calendar: _Calendar
    camera: _Camera
    climate: _Climate
    counter: _Counter
    cover: _Cover
    device_tracker: _DeviceTracker
    event: _Event
    fan: _Fan
    geo_location: _GeoLocation
    humidifier: _Humidifier
    image: _Image
    input_boolean: _InputBoolean
    input_button: _InputButton
    input_datetime: _InputDatetime
    input_number: _InputNumber
    input_select: _InputSelect
    input_text: _InputText
    light: _Light
    lock: _Lock
    media_player: _MediaPlayer
    notify: _Notify
    number: _Number
    person: _Person
    scene: _Scene
    schedule: _Schedule
    script: _Script
    select: _Select
    sensor: _Sensor
    siren: _Siren
    sun: _Sun
    switch: _Switch
    timer: _Timer
    update: _Update
    vacuum: _Vacuum
    water_heater: _WaterHeater
    weather: _Weather
    zone: _Zone
    def __getattr__(self, domain: str) -> _AlarmControlPanel: ...

entities: _EntitiesRegistry
