"""Generated by `hassle stubs` from the registry snapshot. Do not edit by hand."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

class _AutomationServices:
    @staticmethod
    def trigger(
        target: str | Sequence[str] | dict[str, Any] = ...,
        skip_condition: bool | str = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...

class _ClimateServices:
    @staticmethod
    def set_temperature(
        target: str | Sequence[str] | dict[str, Any] = ...,
        temperature: float | str = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...

class _FanServices:
    @staticmethod
    def turn_off(
        target: str | Sequence[str] | dict[str, Any] = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...
    @staticmethod
    def turn_on(
        target: str | Sequence[str] | dict[str, Any] = ...,
        percentage: int | str = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...

class _HomeassistantServices:
    @staticmethod
    def turn_on(
        target: str | Sequence[str] | dict[str, Any] = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...
    @staticmethod
    def update_entity(
        target: str | Sequence[str] | dict[str, Any] = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...

class _InputBooleanServices:
    @staticmethod
    def toggle(
        target: str | Sequence[str] | dict[str, Any] = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...
    @staticmethod
    def turn_off(
        target: str | Sequence[str] | dict[str, Any] = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...
    @staticmethod
    def turn_on(
        target: str | Sequence[str] | dict[str, Any] = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...

class _LightServices:
    @staticmethod
    def toggle(
        target: str | Sequence[str] | dict[str, Any] = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...
    @staticmethod
    def turn_off(
        target: str | Sequence[str] | dict[str, Any] = ...,
        transition: float | str = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...
    @staticmethod
    def turn_on(
        target: str | Sequence[str] | dict[str, Any] = ...,
        brightness: int | str = ...,
        brightness_pct: int | str = ...,
        color_temp: int | str = ...,
        transition: float | str = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...

class _NotifyServices:
    @staticmethod
    def notify(
        target: str | Sequence[str] | dict[str, Any] = ...,
        message: str = ...,
        title: str = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...

class _ScheduleServices:
    @staticmethod
    def reload(
        target: str | Sequence[str] | dict[str, Any] = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...

class _ScriptServices:
    @staticmethod
    def turn_on(
        target: str | Sequence[str] | dict[str, Any] = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...

class _SwitchServices:
    @staticmethod
    def toggle(
        target: str | Sequence[str] | dict[str, Any] = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...
    @staticmethod
    def turn_off(
        target: str | Sequence[str] | dict[str, Any] = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...
    @staticmethod
    def turn_on(
        target: str | Sequence[str] | dict[str, Any] = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...

class _TimerServices:
    @staticmethod
    def cancel(
        target: str | Sequence[str] | dict[str, Any] = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...
    @staticmethod
    def start(
        target: str | Sequence[str] | dict[str, Any] = ...,
        duration: str = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...

class _VacuumServices:
    @staticmethod
    def return_to_base(
        target: str | Sequence[str] | dict[str, Any] = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...
    @staticmethod
    def start(
        target: str | Sequence[str] | dict[str, Any] = ...,
        metadata: dict[str, Any] = ...,
        response_variable: str = ...,
        alias: str = ...,
        enabled: bool = ...,
        continue_on_error: bool = ...,
    ) -> None: ...

automation: _AutomationServices
climate: _ClimateServices
fan: _FanServices
homeassistant: _HomeassistantServices
input_boolean: _InputBooleanServices
light: _LightServices
notify: _NotifyServices
schedule: _ScheduleServices
script: _ScriptServices
switch: _SwitchServices
timer: _TimerServices
vacuum: _VacuumServices

def __getattr__(name: str) -> _AutomationServices: ...  # pyright: ignore[reportIncompleteStub]
