"""Generated by `hassle stubs` from the registry snapshot. Do not edit by hand."""

from __future__ import annotations

class _AutomationServices:
    @staticmethod
    def trigger(skip_condition: bool | str = ...) -> None: ...

class _ClimateServices:
    @staticmethod
    def set_temperature(temperature: float | str = ...) -> None: ...

class _FanServices:
    @staticmethod
    def turn_off() -> None: ...
    @staticmethod
    def turn_on(percentage: int | str = ...) -> None: ...

class _HomeassistantServices:
    @staticmethod
    def turn_on() -> None: ...
    @staticmethod
    def update_entity() -> None: ...

class _InputBooleanServices:
    @staticmethod
    def toggle() -> None: ...
    @staticmethod
    def turn_off() -> None: ...
    @staticmethod
    def turn_on() -> None: ...

class _LightServices:
    @staticmethod
    def toggle() -> None: ...
    @staticmethod
    def turn_off(transition: float | str = ...) -> None: ...
    @staticmethod
    def turn_on(
        brightness: int | str = ...,
        brightness_pct: int | str = ...,
        color_temp: int | str = ...,
        transition: float | str = ...,
    ) -> None: ...

class _NotifyServices:
    @staticmethod
    def notify(message: str = ..., title: str = ...) -> None: ...

class _ScheduleServices:
    @staticmethod
    def reload() -> None: ...

class _ScriptServices:
    @staticmethod
    def turn_on() -> None: ...

class _SwitchServices:
    @staticmethod
    def toggle() -> None: ...
    @staticmethod
    def turn_off() -> None: ...
    @staticmethod
    def turn_on() -> None: ...

class _TimerServices:
    @staticmethod
    def cancel() -> None: ...
    @staticmethod
    def start(duration: str = ...) -> None: ...

class _VacuumServices:
    @staticmethod
    def return_to_base() -> None: ...
    @staticmethod
    def start() -> None: ...

automation: _AutomationServices
climate: _ClimateServices
fan: _FanServices
homeassistant: _HomeassistantServices
input_boolean: _InputBooleanServices
light: _LightServices
notify: _NotifyServices
schedule: _ScheduleServices
script: _ScriptServices
switch: _SwitchServices
timer: _TimerServices
vacuum: _VacuumServices

def __getattr__(name: str) -> _AutomationServices: ...  # pyright: ignore[reportIncompleteStub]
