"""The user-facing DSL callables, in one place (re-exported by the ``hassle`` pkg).

The top-level :mod:`hassle` package (the import surface bundles use, F3) re-exports
from here. Tests and tools can import the same names from a stable module without
depending on the ``hassle`` package layout. Everything here lives in ``hassle_core``
so it is covered by ``pyright --strict``.

``__all__`` here must always equal ``hassle.__all__`` exactly (same 72 names,
same F3 surface) — ``test_dsl_builtins_parity`` in
``packages/hassle-core/tests/test_integration_api.py`` pins this so the two
lists can never silently diverge again (they did: this module used to carry
only 41 of the 72 names).
"""

from __future__ import annotations

from hassle_core.compiler import (
    CompileTimeBranchError,
    ElseWithoutIfError,
    NoParamContextError,
    UnknownParamError,
    all_of,
    any_of,
    area,
    automation,
    blueprint_automation,
    calendar,
    choose,
    counter,
    delay,
    device,
    device_id,
    else_if,
    else_then,
    event,
    expr,
    fire_event,
    floor,
    geo_location,
    homeassistant_shutdown,
    homeassistant_start,
    hours,
    if_then,
    input_boolean,
    input_button,
    input_datetime,
    input_number,
    input_select,
    input_text,
    label,
    macro,
    met,
    minutes,
    mqtt,
    not_,
    numeric_state,
    on,
    only_if,
    parallel,
    param,
    persistent_notification,
    raw_action,
    raw_automation,
    raw_condition,
    raw_trigger,
    repeat_count,
    repeat_for_each,
    repeat_until,
    repeat_while,
    schedule,
    script,
    seconds,
    service,
    shared_script,
    state,
    stop,
    sun,
    tag,
    template,
    time,
    time_pattern,
    timer,
    trigger_condition,
    variables,
    wait_for,
    wait_template,
    webhook,
    when,
    zone,
)

__all__ = [
    "CompileTimeBranchError",
    "ElseWithoutIfError",
    "NoParamContextError",
    "UnknownParamError",
    "all_of",
    "any_of",
    "area",
    "automation",
    "blueprint_automation",
    "calendar",
    "choose",
    "counter",
    "delay",
    "device",
    "device_id",
    "else_if",
    "else_then",
    "event",
    "expr",
    "fire_event",
    "floor",
    "geo_location",
    "homeassistant_shutdown",
    "homeassistant_start",
    "hours",
    "if_then",
    "input_boolean",
    "input_button",
    "input_datetime",
    "input_number",
    "input_select",
    "input_text",
    "label",
    "macro",
    "met",
    "minutes",
    "mqtt",
    "not_",
    "numeric_state",
    "on",
    "only_if",
    "parallel",
    "param",
    "persistent_notification",
    "raw_action",
    "raw_automation",
    "raw_condition",
    "raw_trigger",
    "repeat_count",
    "repeat_for_each",
    "repeat_until",
    "repeat_while",
    "schedule",
    "script",
    "seconds",
    "service",
    "shared_script",
    "state",
    "stop",
    "sun",
    "tag",
    "template",
    "time",
    "time_pattern",
    "timer",
    "trigger_condition",
    "variables",
    "wait_for",
    "wait_template",
    "webhook",
    "when",
    "zone",
]
