"""The `.pyi` stub generator (DESIGN §5.2, MILESTONES M3 test 5).

Generates typed domain classes + per-entity typed attributes matching the
`hassle.registry.entities` attribute/index shape (docs/dsl-f3.md), so a bad
attribute name becomes a pyright error, and typed service methods from
`get_services` schemas.

Digit-leading object_ids (`sensor.3d_printer`) get the underscore-prefix
attribute name (`_3d_printer`) plus a comment naming the real entity_id, and
every domain class also supports `__getitem__` indexing so `e.sensor["3d_printer"]`
still works (the universal escape hatch, DESIGN §5.2).

**Deviation from DESIGN's illustrative snippet:** DESIGN §5.2 shows
`LightEntity.turn_on(brightness_pct: int | Template = ..., transition: float =
...)`. There is no `Template` type anywhere in this codebase (verified: only
`TemplateExpr`, an internal, non-public builder class per docs/dsl-f3.md) --
using it in a *public* generated stub would require exporting an internal
name. This generator instead widens numeric/bool fields to also accept `str`
(the shape a Jinja template string renders as at the type level, since HA
accepts a template string wherever it accepts the field's native type) --
e.g. `brightness_pct: int | str = ...` -- documented here rather than
introducing a new public type as part of an unrelated milestone.
"""

from __future__ import annotations

from hassle.registry.snapshot import RegistrySnapshot, ServiceDef

_PY_TYPE = {
    "integer": "int",
    "int": "int",
    "float": "float",
    "number": "float",
    "string": "str",
    "str": "str",
    "boolean": "bool",
    "bool": "bool",
}


def _domain_class_name(domain: str) -> str:
    """``light`` -> ``_Light``, ``binary_sensor`` -> ``_BinarySensor``."""
    return "_" + "".join(part.capitalize() for part in domain.split("_"))


def _entity_type_name(domain: str) -> str:
    """``light`` -> ``LightEntity``, ``binary_sensor`` -> ``BinarySensorEntity``."""
    return "".join(part.capitalize() for part in domain.split("_")) + "Entity"


def _attr_name(object_id: str) -> str:
    """Digit-leading object_ids get a single underscore prefix (DESIGN §5.2)."""
    if object_id and object_id[0].isdigit():
        return f"_{object_id}"
    return object_id


def _field_type(field_type: str | None) -> str:
    py = _PY_TYPE.get(field_type or "")
    if py is None:
        return "str"
    if py == "str":
        return "str"
    return f"{py} | str"


def _service_method(service_name: str, service_def: ServiceDef) -> list[str]:
    params = ["self"]
    for field_name, field in sorted(service_def.fields.items()):
        py_type = _field_type(field.type)
        params.append(f"{field_name}: {py_type} = ...")
    joined = ", ".join(params)
    one_line = f"    def {service_name}({joined}) -> None: ..."
    if len(one_line) <= 100:
        return [one_line]
    # Wrap one parameter per line (R7 line-length convention) rather than
    # overflow -- a generated stub with many typed fields (e.g. `light.turn_on`)
    # can easily exceed 100 columns on one line.
    lines = [f"    def {service_name}("]
    for param in params:
        lines.append(f"        {param},")
    lines.append("    ) -> None: ...")
    return lines


def generate_entities_stub(snapshot: RegistrySnapshot) -> str:
    """Generate ``entities.pyi`` content from a registry snapshot."""
    domains: dict[str, list[str]] = {}
    for entity in snapshot.entities:
        domain, _, object_id = entity.entity_id.partition(".")
        domains.setdefault(domain, []).append(object_id)

    lines: list[str] = [
        '"""Generated by `hassle stubs` from the registry snapshot. Do not edit by hand."""',
        "",
        "from __future__ import annotations",
        "",
    ]

    # --- one typed entity class per domain, with typed service methods ------
    # Matches `ruff format`'s `.pyi`-aware style: an empty class collapses to
    # `class X: ...` on one line with no blank line before the next empty
    # class, so the generated golden is format-clean without shelling out to
    # ruff at generation time.
    prev_was_empty = False
    for domain in sorted(domains):
        entity_type = _entity_type_name(domain)
        services = snapshot.services.get(domain, {})
        method_lines: list[str] = []
        for service_name in sorted(services):
            method_lines.extend(_service_method(service_name, services[service_name]))
        if method_lines:
            if lines and lines[-1] != "":
                lines.append("")
            lines.append(f"class {entity_type}:")
            lines.extend(method_lines)
            lines.append("")
            prev_was_empty = False
        else:
            if not prev_was_empty and lines and lines[-1] != "":
                lines.append("")
            lines.append(f"class {entity_type}: ...")
            prev_was_empty = True
    if lines and lines[-1] != "":
        lines.append("")

    # --- one domain accessor class per domain, attribute + index access -----
    for domain in sorted(domains):
        class_name = _domain_class_name(domain)
        entity_type = _entity_type_name(domain)
        object_ids = sorted(domains[domain])
        lines.append(f"class {class_name}:")
        for object_id in object_ids:
            attr = _attr_name(object_id)
            entity = next(e for e in snapshot.entities if e.entity_id == f"{domain}.{object_id}")
            comment_bits = [f"{domain}.{object_id}"]
            if entity.name:
                comment_bits.append(f'"{entity.name}"')
            line = f"    {attr}: {entity_type}  # {' - '.join(comment_bits)}"
            if len(line) > 100:
                # Keep the real entity_id (the load-bearing part, needed for the
                # digit-leading rule) and drop the display-name comment rather
                # than overflow the line-length convention (R7).
                line = f"    {attr}: {entity_type}  # {domain}.{object_id}"
            lines.append(line)
        lines.append(f"    def __getitem__(self, object_id: str) -> {entity_type}: ...")
        lines.append("")

    # --- the `entities` accessor itself --------------------------------------
    first_domain_class = _domain_class_name(sorted(domains)[0])
    lines.append("class _EntitiesRegistry:")
    for domain in sorted(domains):
        lines.append(f"    {domain}: {_domain_class_name(domain)}")
    lines.append(f"    def __getattr__(self, domain: str) -> {first_domain_class}: ...")
    lines.append("")
    lines.append("entities: _EntitiesRegistry")
    lines.append("")

    return "\n".join(lines)
