"""``hassle`` — the user-facing DSL import surface (DESIGN §5.3).

Bundle files write ``from hassle import automation, when, ...``. This package is
the *public* face of the DSL; the machinery lives in :mod:`hassle_core`. Physical
home (decision, M1): a second top-level package shipped inside the ``hassle-core``
distribution (``packages/hassle-core/src/hassle``), so there is exactly one wheel
to install and the public surface and its implementation version together.

``__all__`` here is the **F3 freeze candidate** declared at the end of M1: additions
are allowed in later milestones, changes are not (R5). See ``docs/dsl-f3.md``.
"""

from __future__ import annotations

from hassle_core.compiler import (
    CompileTimeBranchError,
    ElseWithoutIfError,
    NoParamContextError,
    UnknownParamError,
    all_of,
    any_of,
    area,
    automation,
    calendar,
    choose,
    delay,
    device,
    device_id,
    else_if,
    else_then,
    event,
    expr,
    floor,
    geo_location,
    homeassistant_shutdown,
    homeassistant_start,
    hours,
    if_then,
    label,
    macro,
    met,
    minutes,
    mqtt,
    not_,
    numeric_state,
    on,
    only_if,
    parallel,
    param,
    persistent_notification,
    raw_action,
    raw_condition,
    raw_trigger,
    repeat_count,
    repeat_for_each,
    repeat_until,
    repeat_while,
    script,
    seconds,
    service,
    service_ext,
    shared_script,
    state,
    stop,
    sun,
    tag,
    template,
    time,
    time_pattern,
    trigger_condition,
    variables,
    wait_for,
    wait_template,
    webhook,
    when,
    with_trigger_options,
    zone,
)

__all__ = [
    "CompileTimeBranchError",
    "ElseWithoutIfError",
    "NoParamContextError",
    "UnknownParamError",
    "all_of",
    "any_of",
    "area",
    "automation",
    "calendar",
    "choose",
    "delay",
    "device",
    "device_id",
    "else_if",
    "else_then",
    "event",
    "expr",
    "floor",
    "geo_location",
    "homeassistant_shutdown",
    "homeassistant_start",
    "hours",
    "if_then",
    "label",
    "macro",
    "met",
    "minutes",
    "mqtt",
    "not_",
    "numeric_state",
    "on",
    "only_if",
    "parallel",
    "param",
    "persistent_notification",
    "raw_action",
    "raw_condition",
    "raw_trigger",
    "repeat_count",
    "repeat_for_each",
    "repeat_until",
    "repeat_while",
    "script",
    "seconds",
    "service",
    "service_ext",
    "shared_script",
    "state",
    "stop",
    "sun",
    "tag",
    "template",
    "time",
    "time_pattern",
    "trigger_condition",
    "variables",
    "wait_for",
    "wait_template",
    "webhook",
    "when",
    "with_trigger_options",
    "zone",
]
