"""Compiler-surface errors (R6: what / where / fix, one paragraph, snapshot-tested).

Every message names *what* went wrong, *where* (file:line where determinable), and
*the fix*, in a single paragraph. These are product surface — the agent docs (§12)
depend on them and they are snapshot-tested (tests/snapshots/errors/).
"""

from __future__ import annotations

from typing import ClassVar

from hassle.compiler.spans import SourceSpan


class CompileError(Exception):
    """Base class for all compile-time errors Hassle raises."""


class CompileTimeBranchError(CompileError):
    """Raised when Python ``if``/``bool()`` is used on a runtime state expression.

    DESIGN §5.5: condition/state expressions define ``__bool__`` to raise this so a
    native Python branch on a runtime value cannot silently compile wrong — it fails
    loudly with a teaching error pointing at the ``with if_then(...)`` rewrite.
    """

    def __init__(self, expr_repr: str, span: SourceSpan | None) -> None:
        where = f" at {span.file}:{span.line}" if span is not None else ""
        self.span = span
        super().__init__(
            f"You used a Python `if`/`bool()` on the runtime state expression "
            f"`{expr_repr}`{where}. Python control flow runs at compile time, so a "
            f"branch on a live entity state would be evaluated once during compilation "
            f"and baked in wrong — never re-checked at runtime. Fix: express the branch "
            f"with a runtime construct, e.g. `with if_then({expr_repr}):` (and "
            f"`with else_then():` for the else arm), which compiles to HA's `if`/`choose`."
        )


# The exact marker comment `hassle.decompiler.splice`/`hassle.sync.source_writer`
# stamp onto a UI-edit appended by `SplicingSourceWriter.splice_object`'s
# stale-manifest/metaprogrammed-object fallback (that module's docstring: a
# compile-time loop's generated object has no single literal statement for the
# splicer to target, so the refreshed definition is appended standalone
# instead). Duplicated here (not imported from `hassle.decompiler.splice`)
# because `hassle.compiler` sits below `hassle.decompiler` in the dependency
# order -- this is a plain string match against the line just above a
# declaration site, not a layering dependency.
_UI_SPLICE_MARKER_PREFIX = "# hassle: updated from UI on"


def _line_is_ui_splice_marker(file_path: str, line: int) -> bool:
    """True if the line immediately before ``line`` (1-based) in ``file_path``
    is the `# hassle: updated from UI on <date>` append marker -- i.e. this
    declaration site is a UI edit `SplicingSourceWriter` appended because it
    couldn't find the object's real (metaprogrammed) declaration to splice
    into. Best-effort: any I/O or index problem just means "no" (this is
    diagnostic framing for an error message, never load-bearing)."""
    try:
        from pathlib import Path

        lines = Path(file_path).read_text(encoding="utf-8").splitlines()
    except OSError:
        return False
    marker_line_no = line - 1  # 1-based line -> 0-based index of the line before it
    if marker_line_no < 1 or marker_line_no > len(lines):
        return False
    return lines[marker_line_no - 1].strip().startswith(_UI_SPLICE_MARKER_PREFIX)


class DuplicateObjectError(CompileError):
    """Two registered objects resolve to the same object key (id collision).

    A special case (polish-batch item 3): this can arise from a **loop-splice
    reconcile** -- ``object_key`` is generated by a compile-time loop
    (metaprogramming, e.g. ``for room in ROOMS: @automation(id=f"motion_{room}")``),
    so when the HA UI edits that specific generated object, `pull`'s splicer
    can't find a single literal statement to replace (the def is inside the
    loop, parameterized) and appends the refreshed definition standalone under
    a ``# hassle: updated from UI on <date>`` marker instead (never dropping
    the edit, I6) -- the NEXT compile then sees two declarations of the same
    id: the original loop iteration and the appended standalone def. When
    either declaration site is immediately preceded by that marker, the
    message names this situation explicitly and points at the reconcile
    flow, on top of the ordinary "name both sites" text.
    """

    def __init__(
        self, object_key: str, first: SourceSpan | None, second: SourceSpan | None
    ) -> None:
        self.object_key = object_key
        loc_a = f"{first.file}:{first.line}" if first is not None else "<unknown>"
        loc_b = f"{second.file}:{second.line}" if second is not None else "<unknown>"
        message = (
            f"Duplicate object key `{object_key}`: two objects in this bundle claim the "
            f"same id, first at {loc_a} and again at {loc_b}. An object's id is its HA "
            f"identity and must be unique bundle-wide. Fix: give one of them a distinct "
            f"`id=` (or rename the function, whose name is the default id)."
        )
        is_splice_reconcile = any(
            span is not None and _line_is_ui_splice_marker(span.file, span.line)
            for span in (first, second)
        )
        if is_splice_reconcile:
            message += (
                " This looks like a loop-splice reconcile: one of these is generated by "
                "metaprogramming (a compile-time loop) and the other is a UI edit `hassle "
                "pull` appended under a `# hassle: updated from UI on <date>` marker because "
                "it couldn't find the generated object's literal statement to splice into. "
                "Reconcile by hand -- fold the UI edit into the loop, extract this object out "
                "of the loop, or delete the appended block -- then re-run `hassle validate`."
            )
        super().__init__(message)


class UnknownAutomationOptionError(CompileError):
    """``@automation`` (or ``@script``) got a keyword it does not accept."""

    def __init__(self, option: str, allowed: list[str], span: SourceSpan | None) -> None:
        self.option = option
        where = f" at {span.file}:{span.line}" if span is not None else ""
        allowed_str = ", ".join(sorted(allowed))
        super().__init__(
            f"Unknown automation option `{option}`{where}. `@automation` accepts only HA's "
            f"automation options: {allowed_str}. Fix: remove `{option}=` or correct its "
            f"spelling; per-object runtime data belongs in `variables=`/`trigger_variables=`, "
            f"not as a decorator keyword."
        )


class ElseWithoutIfError(CompileError):
    """``else_then``/``else_if`` used when the preceding action isn't an ``if``/``choose``.

    DESIGN §5.5: ``with else_then():`` and ``with else_if(...):`` must attach to
    the action recorded immediately before them in the same action list. Used
    at the start of a list, or after some other action, they have nothing to
    attach to.
    """

    def __init__(self, call: str, span: SourceSpan | None) -> None:
        self.call = call
        where = f" at {span.file}:{span.line}" if span is not None else ""
        super().__init__(
            f"`with {call}(...):`{where} does not immediately follow an `if_then`/"
            f"`choose`/`else_if` action in the same action list. HA's `if`/`choose` "
            f"else-branch is a structural part of that action, so `{call}` must be "
            f"the very next statement after the `with if_then(...):`/`with choose():` "
            f"(or `else_if`) block it belongs to. Fix: move `with {call}(...):` "
            f"directly after its `if`/`choose`, with no other action recorded in "
            f"between."
        )


class InvalidCategoryGlobalError(CompileError):
    """A bundle file's module-level ``CATEGORY`` global is not a ``str``
    (MILESTONES M12: category display names via the ``CATEGORY`` global).

    ``CATEGORY`` is read directly off the imported module's namespace (like a
    plain Python global, not a DSL call) — the only shape it may legally take
    is a ``str``, the exact display name pull writes and push uses when it
    has to create a brand-new HA UI category. Anything else (an int, a
    template expression, ``None``, ...) is a compile-time error rather than a
    silent coercion or a silently-ignored value, matching R6.
    """

    def __init__(self, file: str, value: object) -> None:
        self.file = file
        self.value = value
        type_name = type(value).__name__
        article = "an" if type_name[:1].lower() in "aeiou" else "a"
        super().__init__(
            f"`CATEGORY` in {file} is {article} {type_name} ({value!r}), not a `str`. "
            f"`CATEGORY` supplies the exact display name Hassle uses when it has to create a "
            f"brand-new Home Assistant UI category, so it must be a plain string. Fix: quote "
            f'the value, e.g. `CATEGORY = "{value}"`.'
        )


class NoRecordingContextError(CompileError):
    """A recording call (``when``/``only_if``/service/``delay``) ran outside a context.

    This happens when DSL recording calls are made at module scope instead of inside
    an ``@automation``/``@script`` body (which the compiler invokes inside a context).
    """

    def __init__(self, call: str, span: SourceSpan | None) -> None:
        where = f" at {span.file}:{span.line}" if span is not None else ""
        super().__init__(
            f"`{call}` was called outside any recording context{where}. Trigger, condition "
            f"and action calls only make sense inside an `@automation`/`@script` function "
            f"body, which the compiler runs inside a recording context. Fix: move this call "
            f"into a decorated function body; if you meant to build a value, assign the "
            f"builder to a variable instead of calling `{call}` at module scope."
        )


class MissingTemplateHelperWriteTargetError(CompileError):
    """A ``template_number``/``template_select`` declaration omitted its
    required write-target kwarg.

    DESIGN §5.7 / docs/ha-api-notes.md §26.6: HA's `template` config-flow form
    schema requires a write-target action sequence for any writable template
    helper -- ``template_number`` needs ``set_value``, ``template_select``
    needs ``select_option`` -- since ``state`` alone only computes the
    displayed value. Previously this only surfaced as a bare backend
    ``ValueError`` at APPLY time (`_check_required_fields` in
    ``hassle.backend.direct``/``hassle.backend.fake``, kept as a second line
    of defense for non-DSL paths); this is the compile-time product-surface
    version so ``hassle validate``/``hassle plan`` catch it before push.
    """

    # One realistic one-line example action per write-target field, keyed by
    # the exact kwarg name (`set_value` for `template_number`, `select_option`
    # for `template_select`) so the fix example always matches the domain
    # that's actually missing it.
    _EXAMPLE_ACTION: ClassVar[dict[str, str]] = {
        "set_value": (
            '{"action": "input_number.set_value", "target": '
            '{"entity_id": "input_number.example"}, "data": {"value": "{{ value }}"}}'
        ),
        "select_option": (
            '{"action": "input_select.select_option", "target": '
            '{"entity_id": "input_select.example"}, "data": {"option": "{{ option }}"}}'
        ),
    }

    def __init__(self, domain: str, name: str, field: str, span: SourceSpan | None) -> None:
        self.domain = domain
        self.field = field
        self.span = span
        where = f" at {span.file}:{span.line}" if span is not None else ""
        example_action = self._EXAMPLE_ACTION.get(field, "{...}")
        super().__init__(
            f"`{domain}(name={name!r}, ...)`{where} is missing the required `{field}=` "
            f"keyword. HA's `template` config flow requires a write-target action "
            f"sequence for a writable `{domain}` helper -- `state` alone only computes "
            f"the displayed value, so the form schema rejects a submission without one. "
            f"Fix: pass `{field}=` with the action (or list of actions) to run when the "
            f"helper is written from the UI/a service call, e.g. "
            f"`{domain}(name={name!r}, ..., {field}={example_action})`."
        )


class DanglingTemplateHelperDeclarationError(CompileError):
    """A ``template_number``/``template_sensor``/``template_binary_sensor``/
    ``template_select`` call omitted ``state=`` (M13's decorator-form
    signal) but was never applied as a decorator over a function -- so
    nothing was ever built or registered (reviewer finding B1 on the M13
    PR): on the pre-M13 call form, the same bare
    ``template_sensor(name="Ghost Sensor")`` line registered a (degenerate,
    ``state=None``) object; after M13 added decorator detection, omitting
    ``state=`` without following up with ``@...`` over a ``def`` makes the
    call a no-op that COMPILES CLEAN with the object simply absent --a
    silent regression, and an I6 hazard: if that helper already exists in
    HA, its declaration vanishing from the compiled set schedules a DELETE
    of the live object on the next plan/push.

    Caught by a compile-end sweep (:mod:`hassle.compiler.bundle`'s
    ``compile_registered``, the shared core both ``compile_bundle`` and any
    direct caller go through) over every ``TemplateHelperDeclaration``
    created without ``state=`` that was never consumed as a decorator --
    analogous to :class:`NoRecordingContextError` for a bare recording verb
    called outside its context.
    """

    def __init__(self, builder: str, name: str, span: SourceSpan | None) -> None:
        self.builder = builder
        self.span = span
        where = f" at {span.file}:{span.line}" if span is not None else ""
        example_call = f'{builder}(name={name!r}, state="{{{{ ... }}}}")'
        super().__init__(
            f"`{builder}(name={name!r})`{where} has no `state=` and was never used as a "
            f"decorator -- this declaration does nothing (no `{builder}` object is built "
            f"or registered). Fix: either add `state=...` to make this a direct "
            f"declaration (the call form, e.g. `{example_call}`), "
            f"or apply it as a decorator over a zero-arg function, e.g. "
            f"`@{builder}(name={name!r})` followed by `def ...(): return ...`."
        )


class TemplateHelperDecoratorBodyError(CompileError):
    """A ``@template_number``/``@template_sensor``/``@template_binary_sensor``/
    ``@template_select`` decorator was applied to a function whose body
    doesn't fit the decorator form's contract (M13, DESIGN §5.4/§5.7): the
    function must take **zero parameters** and **return** a
    :class:`~hassle.compiler.templates.TemplateExpr` or a plain ``str`` (a
    raw Jinja template) -- nothing else. Three ways to trip this:

    - the function declares one or more parameters (the decorator form has no
      way to supply arguments -- it is called once, at decoration time,
      exactly like ``@automation``/``@script`` bodies are run once by the
      compiler, not parameterized);
    - the function calls a recording verb (``service``/``when``/``only_if``/
      ...) -- a template helper's ``state=`` is a single expression, not an
      action sequence, so there is no recording context for it to record
      into;
    - the function returns something other than a ``TemplateExpr``/``str``
      (e.g. ``None``, a number, a list) -- there is nothing to render as the
      ``state=`` Jinja text.
    """

    def __init__(self, builder: str, name: str, reason: str, span: SourceSpan | None) -> None:
        self.builder = builder
        self.reason = reason
        self.span = span
        where = f" at {span.file}:{span.line}" if span is not None else ""
        super().__init__(
            f"`@{builder}(name={name!r}, ...)`{where}: {reason} Fix: the decorated "
            f"function must take no parameters and `return` a template expression "
            f"built from the `hassle.compiler.templates`/`hassle.compiler.math_expr` "
            f"surface (e.g. `return expr('sensor.x') + 1`) or a plain Jinja string -- "
            f"no service calls, no other side effects, exactly one `return`ed value."
        )


class OnlyIfBlockCoverageError(CompileError):
    """``with only_if(...):`` was used but an action was recorded outside it.

    DESIGN §5.3/§5.5 (``ux/dsl-ergonomics``): automation-level ``only_if`` conditions gate
    *every* action in the automation, not just the ones textually nested under it -- HA has
    no notion of a conditional subset of an automation's action list. So the block form is an
    all-or-nothing declaration: once an automation uses ``with only_if(...):``, every action it
    records must live inside that one block, or the block's visual scope would lie about what
    it actually gates. The bare call form (``only_if(cond)`` with no ``with``) has no such
    requirement -- it's unchanged from before this feature existed.
    """

    def __init__(self, span: SourceSpan | None) -> None:
        where = f" at {span.file}:{span.line}" if span is not None else ""
        super().__init__(
            f"An action was recorded outside the `with only_if(...):` block{where}. "
            f"Automation-level conditions gate every action in the automation, not just the "
            f"ones written inside the block -- so once you use the block form, it must "
            f"contain *all* of the automation's actions. Fix: move every action inside the "
            f"`with only_if(...):` block, or switch back to the bare `only_if(...)` call (no "
            f"`with`), which has no such restriction."
        )
